---
title: "IP Tn Library Colonisation"
author: "IP"
date: "2024-09-23"
output: html_document
---
Adapted from BP_paper_Fig2_EM.Rmd by EM+CC.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE)
library(tidyverse)

day3_fill<- c("#e5eff5","#c3deef","#2b8cbe")
day3_col<- c("#bdd7e7","#6aadd6","#004687")
day2_fill<- day3_fill[c(2,3)]
day2_col<- day3_col[c(2,3)]
point = 2
axis_font_size = 12
axis_title_size = 14
```

Feces. 
Salmonella colonization in the feces after bowel prep over 3 days 
```{r}
imo <- "Imogen_Salmonella_Tn_colonisation.csv"
F2C_long<- read_csv(imo, show_col_types = FALSE) %>% 
  select(!Day) %>%
  pivot_longer(cols = starts_with("Day"), names_to="Day", values_to = "feces_CFU")%>%
  mutate(Day = recode(Day, "Day_0" = "0", "Day_1" = "1", "Day_2" = "2", "Day_3" = "3")) %>% 
  mutate(feces_LOD = ifelse(feces_CFU > 40000, "above", "below")) %>% 
  drop_na(., feces_LOD) %>% 
  mutate(Bowel_prep = factor(Bowel_prep, levels = c("Veh", "Bowel Prep")))

C <- F2C_long %>% 
  ggplot(aes(x = Day, y = feces_CFU, fill = Day)) +
  geom_violin(color = NA, scale = "width", width = 0.8, alpha=0.5) +  
  geom_point(position = position_jitterdodge(), aes(color = Day), size = point) +
  labs(
    x = "Day", 
    y = "Salmonella Counts in Feces (CFU/mL)", 
    fill = "Day", colour = "Day"
  ) +
  geom_hline(yintercept = 40000, colour = "red", linetype = "dashed") +
  theme_bw() +
  scale_fill_manual(values = day3_fill) +  # Fill color for the violins
  scale_color_manual(values = day3_col) +  # Fill color for the points
  scale_y_log10(limits = c(1e0, 1e12), labels = scales::trans_format(log10, scales::math_format(10^.x))) +
  theme(
    panel.border = element_rect(color = "black"),
    panel.grid = element_line(colour = "white"),
    axis.title = element_text(size = axis_title_size, colour = "black"), 
    strip.text.x = element_blank(),
    axis.text = element_text(size = axis_font_size, colour = "black"),
    # legend.position = c(0.88,0.90)
  ) +
  ggtitle("Salmonella in feces of BP mice (est.)")

C

stats <- pairwise.wilcox.test(F2C_long$feces_CFU, F2C_long$Day)
print("Wilcox test statistics:")
print(stats[["p.value"]])
ggsave("Figures/IP_ST_Colonization.png", device = "png", height = 4.90, width = 6)

```

Figure 2D. 
Salmonella colonization in the mLN, spleen and liver after bowel prep 
```{r}
F2D_long<- read_csv(imo, show_col_types = FALSE) %>% 
  pivot_longer(cols = c("mLN", "Spleen", "Liver"), names_to="Tissue", values_to = "tissue_CFU")%>%
  mutate(tissue_LOD = ifelse(tissue_CFU > 660, "above", "below")) %>% 
  drop_na(., tissue_LOD) %>% 
  mutate(Bowel_prep = factor(Bowel_prep, levels = c("Veh", "Bowel Prep"))) %>% 
  mutate(Tissue = factor(Tissue, levels = c("mLN", "Spleen", "Liver")))

J_LOD <- F2D_long %>% #just plot the values above the LOD for the violin plot 
  filter(tissue_LOD == "above")

J_LOD_low <- F2D_long %>% #just plot the values above the LOD for the violin plot 
  filter(tissue_LOD == "below")

#I CHANGED x-axis / FILL TO DAY FROM BP and increased scale max
D <- ggplot() +
  geom_violin(data = J_LOD_low, aes(x = Day, y = tissue_CFU, fill = Day), color = NA, scale = "width", width = 0.8,drop=FALSE, alpha=0.5) +
  geom_violin(data = J_LOD, aes(x = Day, y = tissue_CFU, fill = Day), color = NA, scale = "width", width = 0.8, drop=FALSE, alpha=0.5) +
  geom_point(data = F2D_long, aes(x = Day, y = tissue_CFU, color = Day),
    position = position_jitterdodge(jitter.width = 0.4, dodge.width = 0.9),
    size = point, alpha = 1) +
  labs(
    x = "", 
    y = "Salmonella Counts in Tissues (CFU/g)",
    fill="",color=""
  ) +
  theme_bw() + 
  facet_wrap(~Tissue)+
  geom_hline(yintercept = 660, colour = "red", linetype = "dashed") +
  theme_bw() +
  scale_fill_manual(values = day2_fill) +  # Fill color for the violins
  scale_color_manual(values = day2_col) +  # Fill color for the points
  scale_y_log10(limits = c(1e0, 1e12), labels = scales::trans_format(log10, scales::math_format(10^.x))) +
theme(
    panel.border = element_rect(color = "black"),
    panel.grid = element_line(colour = "white"),
    axis.title = element_text(size = axis_title_size, colour = "black"), 
    axis.text = element_text(size = axis_font_size, colour = "black"),
    strip.text = element_text(size = axis_title_size, colour = 'black'),
    strip.text.x = element_text(size = axis_title_size, colour = 'black'),  
    strip.background = element_blank(),  # Remove background
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  ggtitle("Salmonella translocation at 1, 3 days post-BP (est.)")

D

tissues <- unique(F2D_long$Tissue)
for (t in tissues){
  dat <- F2D_long[F2D_long$Tissue==t,]
  wmn <- wilcox.test(tissue_CFU ~ Day, data=dat, exact=FALSE)
  wmn_p <- wmn$p.value
  print(paste("Wilcoxon/MW p-value for ",t,"is",wmn_p,sep=" "))
}

ggsave("Figures/IP_ST_Translocation.png", device = "png", height = 4.90, width = 5.5)

```