---
title: "AS_Translocation"
author: "IP"
date: "2024-09-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyverse)

#Plot setup
peg_fill<- c("#bb8adc", "#f2f18f")
peg_col<- c("#7614b9", "#e4e21e")
point = 2
axis_font_size = 12
axis_title_size = 14
```

Salmonella colonization in the feces after PEG over 6 days
```{r}
data <- "PEG_F0_Salmonella_Counts.csv"
feces_long <- read_csv(data) %>% 
  pivot_longer(cols = starts_with("Day"), names_to="Day", values_to = "feces_CFU")%>%
  mutate(Day = recode(Day, "Day_1" = "1", "Day_2" = "2", "Day_3" = "3",
                      "Day_4"="4","Day_5"="5","Day_6"="6")) %>% 
  mutate(feces_LOD = ifelse(feces_CFU > 100, "above", "below")) %>% 
  drop_na(., feces_LOD) %>% 
  mutate(Treatment = factor(Treatment, levels = c("PEG", "MB-")))

feces <- feces_long %>% 
  ggplot(aes(x = Day, y = feces_CFU, fill = Treatment)) +
  geom_violin(color = NA, scale = "width", width = 0.8) +  
  geom_point(position = position_jitterdodge(), aes(color = Treatment)) +
  labs(
    x = "Day", 
    y = "Salmonella Counts in Feces (CFU/mL)", 
    fill = "", colour = ""
  ) +
  geom_hline(yintercept = 100, colour = "red", linetype = "dashed") +
  theme_bw() +
  scale_fill_manual(values = peg_fill) +  # Fill color for the violins
  scale_color_manual(values = peg_col) +  # Fill color for the points
  scale_y_log10(limits = c(1e0, 1e8), labels = scales::trans_format(log10, scales::math_format(10^.x))) +
  theme(
    panel.border = element_rect(color = "black"),
    panel.grid = element_line(colour = "white"),
    axis.title = element_text(size = axis_title_size, colour = "black"), 
    strip.text.x = element_blank(),
    axis.text = element_text(size = axis_font_size, colour = "black"),
    # legend.position = c(0.88,0.90)
  ) +
  ggtitle("Salmonella in feces of MB- or conventional PEG+")

feces

feces_box <- ggplot(data = feces_long, aes(x = Treatment, y = feces_CFU, 
                                             fill = Treatment,color=Treatment)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width=0.2)+
  labs(x = "", y = "Salmonella Counts in Feces (CFU/mL)",fill="",color="") +
  theme_bw() + 
  facet_grid(~Day)+
  scale_fill_manual(values = peg_fill) +  # Fill color for the violins
  scale_color_manual(values = peg_col) +  # Fill color for the points
  scale_y_log10(limits = c(1e0, 1e7), labels = scales::trans_format(log10, scales::math_format(10^.x))) +
theme(
    panel.border = element_rect(color = "black"),
    panel.grid = element_line(colour = "white"),
    axis.title = element_text(size = axis_title_size, colour = "black"), 
    axis.text = element_text(size = axis_font_size, colour = "black"),
    strip.text = element_text(size = axis_title_size, colour = 'black'),
    # legend.position = c(0.88,0.90),
    strip.text.x = element_text(size = axis_title_size, colour = 'black'),  
    strip.background = element_blank(),  # Remove background
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
    geom_hline(yintercept = 100, colour = "red", linetype = "dashed") +
  ggtitle("Salmonella in feces of MB- or conventional PEG+")
feces_box

# Wilcoxon/Mann-Whitney test (two groups, non-parametric as not-normal)
days <- unique(feces_long$Day)
for (d in days){
  dat <- feces_long[feces_long$Day==d,]
  wmn <- wilcox.test(feces_CFU ~ Treatment, data=dat, exact=FALSE)
  wmn_p <- wmn$p.value
  print(paste("Wilcoxon/MW p-value for day",d,"is",wmn_p,sep=" "))
}

# ggsave("Feces_Colonization_box.pdf", feces_box, device = "pdf", height = 4.90, width = 6)

```

Salmonella translocation in the tissues after 6 days of PEG + infection
```{r}
data <- "PEG_F0_Salmonella_Counts.csv"

tissue_long<- read_csv(data) %>% 
  pivot_longer(cols = c("mLN", "Spleen", "Liver","Cecum"), names_to="Tissue", values_to = "tissue_CFU")%>%
  mutate(Treatment = factor(Treatment, levels = c("PEG", "MB-"))) %>% 
  mutate(Tissue = factor(Tissue, levels = c("mLN", "Spleen", "Liver","Cecum")))

tissue <- ggplot() +
  geom_violin(data = tissue_long, aes(x = Treatment, y = tissue_CFU, fill = Treatment), color = NA, scale = "width", width = 0.8,drop=FALSE) +
  geom_point(data = tissue_long, aes(x = Treatment, y = tissue_CFU, color = Treatment),
    position = position_jitterdodge(jitter.width = 0.4, dodge.width = 0.9),
    size = point, alpha = 1) +
  labs(x = "", y = "Salmonella Counts in Tissues (CFU/g)",fill="",color="") +
  theme_bw() + 
  facet_grid(~Tissue)+
  theme_bw() +
  scale_fill_manual(values = peg_fill) +  # Fill color for the violins
  scale_color_manual(values = peg_col) +  # Fill color for the points
  scale_y_log10(limits = c(1e0, 1e7), labels = scales::trans_format(log10, scales::math_format(10^.x))) +
theme(
    panel.border = element_rect(color = "black"),
    panel.grid = element_line(colour = "white"),
    axis.title = element_text(size = axis_title_size, colour = "black"), 
    axis.text = element_text(size = axis_font_size, colour = "black"),
    strip.text = element_text(size = axis_title_size, colour = 'black'),
    # legend.position = c(0.88,0.90),
    strip.text.x = element_text(size = axis_title_size, colour = 'black'),  
    strip.background = element_blank(),  # Remove background
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  ggtitle("Salmonella translocation at 6 days post-infection")

tissue

tissue_box <- ggplot(data = tissue_long, 
                     aes(x = Treatment, y = tissue_CFU, fill = Treatment,color=Treatment)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width=0.2)+
  labs(x = "", y = "Salmonella Counts in Tissues (CFU/g)",fill="",color="") +
  theme_bw() + 
  facet_grid(~Tissue)+
  scale_fill_manual(values = peg_fill) +  # Fill color for the violins
  scale_color_manual(values = peg_col) +  # Fill color for the points
  scale_y_log10(limits = c(1e0, 1e7), labels = scales::trans_format(log10, scales::math_format(10^.x))) +
theme(
    panel.border = element_rect(color = "black"),
    panel.grid = element_line(colour = "white"),
    axis.title = element_text(size = axis_title_size, colour = "black"), 
    axis.text = element_text(size = axis_font_size, colour = "black"),
    strip.text = element_text(size = axis_title_size, colour = 'black'),
    # legend.position = c(0.88,0.90),
    strip.text.x = element_text(size = axis_title_size, colour = 'black'),  
    strip.background = element_blank(),  # Remove background
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  ggtitle("Salmonella translocation at 6 days post-infection")
tissue_box

tissues <- unique(tissue_long$Tissue)
for (t in tissues){
  dat <- tissue_long[tissue_long$Tissue==t,]
  wmn <- wilcox.test(tissue_CFU ~ Treatment, data=dat, exact=FALSE)
  wmn_p <- wmn$p.value
  print(paste("Wilcoxon/MW p-value for tissue",t,"is",wmn_p,sep=" "))
}

# ggsave("Tissue_Colonization_box.pdf", tissue_box, device = "pdf", height = 4.90, width = 6)
```

Weight loss after infection
```{r}
data <- "weight_loss_data_F0_salmonella_sac.csv"
peg_col2<- c("#7614b9", "#f6f30c")

weight <- read_csv(data) %>%
    mutate(Treatment = factor(Treatment, levels = c("PEG", "MB-"))) 
  
weight_summ <- weight %>%
  group_by(Treatment,Day) %>% 
  summarise(mean=mean(Percent_Change), stdev=sd(Percent_Change))
weight_summ

weigh_plot <- weight_summ %>% 
  ggplot(aes(x=Day,y=mean,group=Treatment,color=Treatment,fill=Treatment)) +
  theme_bw() +
  scale_fill_manual(values = peg_fill) +  # Fill color for the violins
  scale_color_manual(values = peg_col2) +  # Fill color for the points
  geom_ribbon(aes(y = mean, ymin = mean-stdev, ymax = mean+stdev, fill = Treatment), 
              alpha = .6, color=NA) +
  geom_line() +
  geom_point(color="black",pch=21) + 
  ggtitle("Mouse % weight change following Salmonella infection") +
  labs(x="Day",y="Mean % weight change")

weigh_plot
# ggsave("weight_change.png",weigh_plot, device = "png", height = 4.90, width = 6)
```

Bar plots (ew???)
```{r}
#FECES#################
feces_sum <- feces_long %>%
  group_by(Day,Treatment) %>% 
  summarise(mean=mean(feces_CFU,na.rm=TRUE), 
            stdev =sd(feces_CFU,na.rm=TRUE),
            sterr=(sd(feces_CFU)/sqrt(n())))

feces_bar <- feces_sum %>%
  ggplot(aes(x=Treatment,y=mean,fill=Treatment,colour=Treatment))+
  geom_col(position="dodge",alpha=0.7) + 
  facet_grid(~Day)+
  geom_jitter(data = feces_long, 
              aes(x=Treatment,y=feces_CFU,fill=Treatment,colour=Treatment),
              width=0.2) +
  theme_classic() +
  scale_fill_manual(values = peg_fill) +  # Fill color for the violins
  scale_color_manual(values = peg_col) +  # Fill color for the points
  geom_errorbar(aes(ymin= mean - sterr,ymax= mean + sterr, colour=Treatment, width=0.8)) +
  scale_y_log10(limits = c(1e0, 1e8), labels = scales::trans_format(log10, scales::math_format(10^.x))) +
  labs(x="",y="Salmonella Counts in Feces (CFU/mL)")

feces_bar
ggsave("Feces_Colonization_Bar.png",feces_bar, device = "png", height = 4.90, width = 6)


#TISSUE#################
tissue_sum <- tissue_long %>%
  group_by(Tissue,Treatment) %>% 
  summarise(mean=mean(tissue_CFU,na.rm=TRUE), 
            stdev =sd(tissue_CFU,na.rm=TRUE),
            sterr=(sd(tissue_CFU,na.rm=TRUE)/sqrt(n())))

tissue_bar <- tissue_sum %>%
  ggplot(aes(x=Treatment,y=mean,fill=Treatment,colour=Treatment))+
  geom_col(alpha=0.7) +
  geom_jitter(data = tissue_long, 
              aes(x=Treatment,y=tissue_CFU,fill=Treatment,colour=Treatment),
              width=0.2) +
  geom_errorbar(aes(ymin= mean - sterr,ymax= mean + sterr, colour=Treatment, width=0.8)) +
  facet_grid(~Tissue)+
  theme_classic() +
  scale_fill_manual(values = peg_fill) +  # Fill color for the violins
  scale_color_manual(values = peg_col) +  # Fill color for the points
  scale_y_log10(limits = c(1e0, 1e7), labels = scales::trans_format(log10, scales::math_format(10^.x))) +
  labs(x="",y="Salmonella Counts in Tissues (CFU/g)")

tissue_bar
ggsave("Tissue_Colonization_Bar.png",tissue_bar, device = "png", height = 4.90, width = 6)
```