---
title: "DESEq2_analyses"
author: "IP"
date: "2024-07-16"
output: html_document
---

```{r setup, include=FALSE}
load("phyloseq_object_final.RData")
load("tax_matrix.RData") 
library(phyloseq)
library(ape)
library(tidyverse)
library(picante)
library(ggplot2)
library(ggpubr)
library(vegan)
library(DESeq2)
library(microViz)
library(scran)

```
## Defining functions for graphing
```{r graph-functions}
deseq_barplot <- function(d=21,t=c("MB_Clostridia","Mb_only"),v="Treatment",
                          desq_results=desq_results_sig) {
  g <- ggplot(data = desq_results, 
              aes(y = reorder(Genus, -(as.numeric(log2FoldChange))), 
                      x = log2FoldChange, fill = pvalue))+
        geom_col() + 
        labs(x="Log2 Fold Change",
             y="Genus",
             title=(paste("Differential abundance at day",d,"comparing between","\n",
                                   paste(t,collapse=" & "), sep=" ")))
  return(g)
}

#The above function had issues with overlapping bars when the same genus was repeated.
#As a result the plotpoint function is developed so that each is individually visible.
deseq_pointplot <- function(d=21,t=c("MB_Clostridia","Mb_only"),v="Treatment",
                          desq_results=desq_results_sig) {
  g <- ggplot(data = desq_results, 
              aes(y = reorder(Genus, -(as.numeric(log2FoldChange))), 
                      x = log2FoldChange, color = pvalue))+
        geom_point() + 
        labs(x="Log2 Fold Change",
             y="Genus",
             title=(paste("Differential abundance at day",d,"comparing between","\n",
                                   paste(t,collapse=" & "), sep=" ")))
  return(g)
}
``` 

# DESEq2 analysis producing point-plot
```{r }
load("phyloseq_object_final.RData")
load("tax_matrix.RData")

#Filter phyloseq to our day and treatments of interest, and glom by genus
d=21
t=c("MB_Clostridia","Mb_only")

physeq_object <- ps_filter(phyloseq_object_final, day==d, Treatment%in%t) 
physeq_genus <- tax_glom(physeq_object,"Genus")

deseq_object <- phyloseq_to_deseq2(physeq_genus, ~Treatment) %>% DESeq()

deseq_results <- deseq_object %>% results(tidy=TRUE)

colnames(deseq_results)[1] <- "#OTU ID"
deseq_results <- inner_join(tax_matrix,deseq_results, by = "#OTU ID" )

deseq_results_sig <-  deseq_results %>%
  filter(padj<0.05 & abs(log2FoldChange)>1.5)
deseq_results_sig <- deseq_results_sig[order(deseq_results_sig$log2FoldChange),]

deseq_pointplot(d,t,v,deseq_results_sig) + theme_bw() +
    geom_vline(xintercept=0)

```


